" Sherman's .vimrc
"
" Individual bundles were not being added to my runtimepath
set runtimepath+=~/.vim/bundle/*/

" Note: Skip initialization for vim-tiny or vim-small.
if !1 | finish | endif

if has('vim_starting')
	if &compatible
		set nocompatible		   " Be iMproved
	endif

	" Required:
	set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" My Bundles here:
" Refer to |:NeoBundle-examples|.
" Note: You don't set neobundle setting in .gvimrc!
NeoBundleFetch 'https://github.com/kien/ctrlp.vim'
NeoBundleFetch 'https://github.com/rking/ag.vim'
NeoBundleFetch 'https://github.com/dyng/ctrlsf.vim'
NeoBundleFetch 'https://github.com/editorconfig/editorconfig-vim'
NeoBundleFetch 'https://github.com/tpope/vim-fugitive'
NeoBundleFetch 'https://github.com/airblade/vim-gitgutter'
NeoBundleFetch 'https://github.com/christoomey/vim-tmux-navigator'
NeoBundleFetch 'https://github.com/scrooloose/nerdtree'
NeoBundleFetch 'https://github.com/Xuyuanp/nerdtree-git-plugin'
NeoBundleFetch 'https://github.com/sjl/gundo.vim'
NeoBundleFetch 'https://github.com/scrooloose/nerdcommenter'
NeoBundleFetch 'https://github.com/easymotion/vim-easymotion'
NeoBundleFetch 'https://github.com/tpope/vim-surround'

" CSV is something I use infrequently
NeoBundleFetch 'https://github.com/chrisbra/csv.vim'

" makes it a little easier than html highlighting
NeoBundleFetch 'https://github.com/mustache/vim-mustache-handlebars'

" CSS plugins
NeoBundleFetch 'https://github.com/groenewege/vim-less'
NeoBundleFetch 'https://github.com/hail2u/vim-css3-syntax'
NeoBundleFetch 'https://github.com/skammer/vim-css-color'

" Javascript plugins
NeoBundleFetch 'https://github.com/kchmck/vim-coffee-script'
NeoBundleFetch 'https://github.com/pangloss/vim-javascript'
NeoBundleFetch 'https://github.com/pangloss/vim-javascript'

" PHP plugins
NeoBundleFetch 'https://github.com/2072/PHP-Indenting-for-VIm'
NeoBundleFetch 'https://github.com/2072/vim-syntax-for-PHP'

" Debugger for multiple languages
NeoBundleFetch 'https://github.com/joonty/vdebug'

" NeoBundleFetch 'https://github.com/chriskempson/base16-vim'

call neobundle#end()

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck

" Split .vimrc into multiple files, included by glob
" This is to encapsulate functionality into more readable groups
" http://superuser.com/questions/438232/include-all-vim-files-in-a-folder
for rcfile in split(globpath("~/.vim/rc", "*.vim"), '\n') 
	execute('source '.rcfile)
endfor

" For local configuration we need files not in git
" This will load all vim configs in ~/.vim/localconf
" This is the same as loading the rc directory
for rcfile in split(globpath("~/.vim/localconf", "*.vim"), '\n') 
	execute('source '.rcfile)
endfor
